### ISSUE TITLE
Provide questions for Client

### ISSUE THREAD

**Issue by hindeb** [bahrain-bp/mun-aquacrop#12]
1.  Which growth stage is not important? (Init. (Lini), Dev. (Ldev), Mid (Lmid), Late)
2. Should the Farmer add their Name as part of registration to Aquacrop?

3. Provide us for the table for Kc in bahrain (Kc for each crop for each stage)
4. Min and Max Temperature not found in the shared Data with us (only mean Temperature is shared). We need them to find es
5. You have provided the mean radiation and we will be needing the Net Radiation (Rn) meaning Rs - Rns
6. we will assume G = 0.
7. we will assume the Atmosphere P is 101.3 kPa.
8. Daily wind speed provided is for Height of 6m. How to get the u2 for 2 meters.
9.

**Comment by hindeb** [comment]
1. Which growth stage is not important? (Init. (Lini), Dev. (Ldev), Mid (Lmid), Late)

**Comment by chebibj** [comment]
First round of questions were delivered to Customer and answers were provided.
If no additional questions needed, this activity can be closed and moved to Done
