### ISSUE TITLE
USER STORY 3 - Listing Crop

### ISSUE THREAD

**Issue by chebibj** [bahrain-bp/mun-aquacrop#22]
Add here the Technical Requirements for the User Story (US Diagram, What is required technically)

1. S3 bucket for retrieving images
2. API gateway for API requests
3. Application 
4. Crop Table 
5. Lambda function
6.

**Comment by Lui35** [comment]
- [ ] creating the lambda func 

- [ ] Mapping Api

- [ ] Testing the func
