### ISSUE TITLE
Develop Story telling frames

### ISSUE THREAD

**Issue by AliAnnan9** [bahrain-bp/mun-aquacrop#3]
Links:

-  https://www.storyboardthat.com

Update: Hasan fixed the storyboards and finalized it

**Comment by chebibj** [comment]
Follow the Framework for story telling:

1. Show the Problem
2. Show the negative Impact
3. Suggest a Solution
4. Showcase solution (how it works)
5. Solution implemented
6. Positive Impact & Results
7. Outcome

**Comment by izZERO** [comment]
shorten the story a bit to around 8 slides, few slide can be removed and a few could be modified and improved.
add more humor the the story.

**Comment by izZERO** [comment]
-Shortened the story & Removed unnecessary pages
-Moved the financial focus to the real customer (the farm manager)
-Added more Humour

**Comment by izZERO** [comment]
-need to adjust the story to be localized to Bahraini's with the theme and characters using DALL-E ai
-arabic version of the story
-add palms instead of the home garden


*These adjustments were requested from the customer*

**Comment by chebibj** [comment]
This looks like it's completed and can be moved to Done

**Comment by Lui35** [comment]
add irrigation  pump rather than the hose

**Comment by izZERO** [comment]
- [ ] Added Drippers instead of hose
- [ ] Created Arabic Version of the Story
