### ISSUE TITLE
Define Table Users

### ISSUE THREAD

**Issue by izZERO** [bahrain-bp/mun-aquacrop#6]
CREATE TABLE Users (
                UID NUMERIC AUTO_INCREMENT NOT NULL,
                mobile_no NUMERIC(8) NOT NULL,
                reg_date DATE NOT NULL,
                status VARCHAR(10) NOT NULL,
                PRIMARY KEY (UID)
);

**Comment by chebibj** [comment]
Can you add more details for each field?
Field Definition, Data type, size,   etc
