### ISSUE TITLE
Define Table Crops

### ISSUE THREAD

**Issue by izZERO** [bahrain-bp/mun-aquacrop#7]
CREATE TABLE Crops (
                CID NUMERIC AUTO_INCREMENT NOT NULL,
                image_URL VARCHAR(200) NOT NULL,
                name VARCHAR(50) NOT NULL,
                PRIMARY KEY (CID)
);

**Comment by chebibj** [comment]
Can you add more details for each field?
Field Definition, Data type, size,   etc
