### ISSUE TITLE
Define Table Weather Info

### ISSUE THREAD

**Issue by izZERO** [bahrain-bp/mun-aquacrop#8]
(subject to change)
CREATE TABLE WeatherReadings (
                RID NUMERIC AUTO_INCREMENT NOT NULL,
                date DATE NOT NULL,
                radiation NUMERIC(10) NOT NULL,
                air_temp NUMERIC(10) NOT NULL,
                humidity NUMERIC(10) NOT NULL,
                wind_speed NUMERIC(10) NOT NULL,
                PRIMARY KEY (RID)
);

**Comment by chebibj** [comment]
Can you add more details for each field?
Field Definition, Data type, size,   etc
